version: "3.8"

services:
  finance:
    image: fintracker:latest
    networks:
      - network_public
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      labels:
        - "traefik.enable=true"

        # Router HTTPS (principal)
        - "traefik.http.routers.finance-https.rule=Host(`finance.grillo.tec.br`)"
        - "traefik.http.routers.finance-https.entrypoints=websecure"
        - "traefik.http.routers.finance-https.tls=true"
        - "traefik.http.routers.finance-https.tls.certresolver=letsencrypt"

        # Serviço interno (Nginx expõe 80)
        - "traefik.http.services.finance.loadbalancer.server.port=80"

networks:
  network_public:
    external: true
